from sqlalchemy import Column, BigInteger, Integer, Text, DateTime
from .base import Base

class Resource(Base):
    __tablename__ = 'resources'
    __table_args__ = {'schema': 'feed'}

    id_reso = Column(BigInteger, primary_key=True, autoincrement=True)
    id_ern = Column(BigInteger, nullable=False)
    reference_reso = Column(Text)
    isrc_reso = Column(Text)
    technical_detail_reference_reso = Column(Text)
    type_reso = Column(Text, nullable=False)
    is_preview_reso = Column(Text)
    is_url_reso = Column(Integer, default=0, nullable=False)
    file_path_reso = Column(Text)
    file_url_reso = Column(Text)
    audio_codec_type_reso = Column(Text)
    image_codec_type_reso = Column(Text)
    bit_rate_reso = Column(Text)
    number_of_channels_reso = Column(Text)
    sampling_rate_reso = Column(Text)
    bits_per_sample_reso = Column(Text)
    preview_start_point_reso = Column(Integer)
    preview_end_point_reso = Column(Integer)
    preview_duration_reso = Column(DateTime)
    file_hash_sum_reso = Column(Text)
    file_hash_sum_algorithm_type_reso = Column(Text)
    status_processed_128_reso = Column(Text)
    status_processed_result_128_message_reso = Column(Text)
    status_processed_320_reso = Column(Text)
    status_processed_result_320_message_reso = Column(Text)
    status_processed_custom_preview_reso = Column(Text)
    status_processed_result_custom_preview_message_reso = Column(Text)
    status_processed_image_reso = Column(Text)
    status_processed_result_image_message_reso = Column(Text)
    status_copied_to_catalog_128_reso = Column(Text, default='PENDING', nullable=False)
    status_copied_to_catalog_320_reso = Column(Text, default='PENDING', nullable=False)
    status_copied_to_catalog_image_reso = Column(Text, default='PENDING', nullable=False)
    audi_edited_reso = Column(DateTime)
    audi_created_reso = Column(DateTime)