services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: pruebas
      MYSQL_ROOT_PASSWORD: miguel
      MYSQL_USER: miguel
      MYSQL_PASSWORD: miguel
      MYSQL_ROOT_HOST: "%"  # Permite conexiones desde cualquier host
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
    driver: local